# ----------------------------------------------------------------
# PLUGIN WRITED BY AXOLOTLEKKK
#        EffectKills
# PLUGIN WRITED BY AXOLOTLEKKK
# ----------------------------------------------------------------

title:
subtitle:

# ----------------------------------------------------------------

reloaded-in:
reload-message:
error-message:

# ----------------------------------------------------------------
